
def add_tegenrekening_keywords(category):
    names = ['keizer', 'mineur', 'h g poorthuis', 'j berends', 'mw kz lieverse', 'fj sloos']

    category['Totaal'].keywords_naam_tegenrekening = []
    category['Eigen rekeningen'].keywords_naam_tegenrekening = ['wa poorthuis', 'w.a. poorthuis', 'w a poorthuis', 'poorthuis w a', 'Ideaalsparen']
    category['DUO'].keywords_naam_tegenrekening = ['DUO']
    category['Boodschappen'].keywords_naam_tegenrekening = ['albert heijn', 'jumbo', 'AH', 'McD']
    category['Kleding'].keywords_naam_tegenrekening = ['veganwear']
    category['Media'].keywords_naam_tegenrekening = ['steampowered', 'boekenroute', 'games']
    category['Reiskosten'].keywords_naam_tegenrekening = ['ns groep', 'chipkaart', 'NS Utrecht', 'NS Reizigers', 'NS Rotterdam']
    category['Woning'].keywords_naam_tegenrekening = ['donker', 'odekerken', 'ssh']
    category['Drugs'].keywords_naam_tegenrekening = []
    category['Cadeaus'] .keywords_naam_tegenrekening= ['foodelicious']
    category['Terugbetalingen'].keywords_naam_tegenrekening = ['betaalverzoek', 'tikkie', 'abn amro bank nv'] + names
    category['Loon'].keywords_naam_tegenrekening = ['driessen']
    category['Bijdrage familie'].keywords_naam_tegenrekening = ['k mol', 'f.p.m. poorthuis', 'rooseboom']
    category['Belastingen'] .keywords_naam_tegenrekening= ['belastingdienst']
    category['Horeca'].keywords_naam_tegenrekening = ['louis hartlooper', 'takeaway', 'thuisbezorgd']
    category['Feesten'].keywords_naam_tegenrekening = {'ticketing',  'ticketswap'}
    category['Goede doelen'].keywords_naam_tegenrekening = ['milieudefensie', 'wwf', 'hersenstichting']
    category['Vaste lasten'] .keywords_naam_tegenrekening= ['youfone', 'orca', 'paypal', 'Gemeente']
    category['Online bestellingen'].keywords_naam_tegenrekening = ['bol', 'coolblue', 'allekabels', 'alloverpiercings', 'amazon', 'marktplaats']
    category['Zorg'].keywords_naam_tegenrekening = ['unive', 'infomedics', 'fysiotherapie']
    category['Hobbies'].keywords_naam_tegenrekening = []
    category['Vakanties'].keywords_naam_tegenrekening= ['SUPERSTORE']
    category['Spaar'].keywords_naam_tegenrekening= []
    category['Geen categorie'].keywords_naam_tegenrekening = []

def add_omschrijving_keywords(category):

    category['Totaal'].keywords_omschrijving = []
    category['Eigen rekeningen'].keywords_omschrijving = ['eerste inleg']
    category['DUO'].keywords_omschrijving = []
    category['Boodschappen'].keywords_omschrijving = ['jumbo', 'ah', 'albert heijn', 'lidl', 'ekoplaza', 'plus', 'natuurwinkel', 'albertheijn', 'aldi', 'coop', 'netto', 'dirk', 'sweetgreen', 'spar', 'Boon\'s', 'Odin', 'McD', 'BOONS']
    category['Kleding'].keywords_omschrijving = ['Vintage Island', 'De ARM', 'DUMP', 'Episode', 'Book Center']
    category['Media'].keywords_omschrijving = ['AKO', 'Broese', 'ROBBEDOES', 'BOEKHANDEL', 'LantarenVenster']
    category['Reiskosten'].keywords_omschrijving = [ 'Fietsen', 'Fiets', 'BIKE', 'Bike', 'Centraal', 'Giant', 'NS-', 'NS Utrecht', 'NS Reizigers', 'NS Rotterdam']
    category['Woning'].keywords_omschrijving = ['Huisgeld', 'Airbnb']
    category['Drugs'].keywords_omschrijving = ['Pleasure', 'CULTURE', 'ANDERSOM', 'State of Mind']
    category['Cadeaus'].keywords_omschrijving = ['CASA', 'Kinderwin.Westerkade']
    category['Terugbetalingen'].keywords_omschrijving = ['OVERBOEKING VIA INTERNET']
    category['Loon'].keywords_omschrijving = ['SALARIS']
    category['Bijdrage familie'].keywords_omschrijving = []
    category['Belastingen'].keywords_omschrijving = []
    category['Horeca'].keywords_omschrijving = ['Ledig Erf', 'Orca', 'Falafel City', 'Orloff', 'Cafe', 'Vegan', 'Dikke Dries', 'Smullers', 'Lunchroom', 'Manneken Pis', 'Eethuis', 'Ladage', 'eten', 'DONER', 'Una Mas', 'Poema', 'SLA', 'LaPlace', 'Pandje', 'Snackbar', 'Food Village', 'Barlow', 'KOFFIE']
    category['Feesten'].keywords_omschrijving = ['Festival', 'TIVOLI', 'EKKO', 'GROTE ZAAL', 'Filmcafe']
    category['Goede doelen'].keywords_omschrijving = []
    category['Vaste lasten'].keywords_omschrijving = ['RENTE']
    category['Online bestellingen'].keywords_omschrijving = []
    category['Zorg'].keywords_omschrijving = ['fysiotherapie']
    category['Hobbies'].keywords_omschrijving = ['Pipoos', 'Kathmandu']
    category['Vakanties'].keywords_omschrijving = ['Bever']
    category['Spaar'].keywords_omschrijving= []
    category['Geen categorie'].keywords_omschrijving = []
